#!/usr/bin/env python
# coding=utf-8


__author__ = 'Kentaro Sasaki'
__copyright__ = 'Copyright 2013 Kentaro Sasaki'


import argparse
import subprocess
import sys


def exec_call(cmd):
  """Execute function.

  Args:
    cmd: command line strings from sssh function.

  Returns:
    Truth value of command line result.
  """
  return subprocess.check_call(cmd, shell=True)


def sssh(host):
  """Command line strings.

  Args:
    host: host name to do ssh.

  Returns:
    Strings for running ssh with screen.
  """
  return ('/usr/bin/screen -t %s /usr/bin/ssh -A %s' % (host, host))


def executor(host):
  """Exception handler for running execute function.

  This uses exec_call function to run sssh function.

  Args:
    host: host name to do ssh.
  """
  try:
    exec_call(sssh(host))
  except Exception as msg:
    print('%s' % str(msg))
    pass


def option():
  """Get host name from command line.

  This gets host name from sys.stdin using argparse module.

  Returns:
    Option to get host name.
  """
  parser = argparse.ArgumentParser(description='ssh with screen')
  parser.add_argument('host', type=str, default=sys.stdin)

  return parser.parse_args()


def main():
  """Run ssh with screen.

  This runs ssh, at the same time this runs screen.
  You can use option to set the host name or IP address.

  """
  executor(option().host)


if __name__ == '__main__':
  main()
